### ISSUE TITLE
`RFENCE`扩展性能优化

### ISSUE THREAD

**Issue by guttatus** [rustsbi/rustsbi#99]
## 需求描述
在多核或众核场景下，调用`RFENCE`扩展的接口（如`remote_sfence_vma`）耗时较大，需要探索`RFENCE`拓展的性能优化策略。
需要完成以下工作：

## TODO

- [x] 构建Benchmark，测量不同SBI实现的`remote_sfence_vma`调用耗时
- [ ] 分析`remote_sfence_vma`等接口实现的热点代码
- [ ] 探索`RFENCE`扩展的性能优化策略
